set_property SRC_FILE_INFO {cfile:/home/lukasjoc/builds/digilent-xdc/Zybo-Z7-Master.xdc rfile:../../../../../../../builds/digilent-xdc/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { i_sw_0 }]; #IO_L19N_T3_VREF_35 Sch=sw[0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { o_led_0 }]; #IO_L23P_T3_35 Sch=led[0]
